version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5442:5432"
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    command: sh -c "npx typeorm-ts-node-commonjs migration:run -d ./src/data-source.ts && npm start"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
